### ISSUE TITLE
React-Modal: injectCSS has been deprecated and no longer has any effect. It will be removed in a later version

### ISSUE THREAD

**Issue by stelt** [enjalot/blockbuilder#122]
that's what I read in my browser's console

**Comment by seemantk** [comment]
Google is very not helpful at all with this message.  Zero hits.  There is only one mention [react-modal's ChangeLog](https://github.com/reactjs/react-modal/blob/1a0a069a7f91aa660433bdfa410636d4e3d81fcf/CHANGELOG.md).

and [the referenced commit](https://github.com/reactjs/react-modal/commit/4d25989) has documentation on the new usage.

Does that mean [line 47](https://github.com/enjalot/blockbuilder/blob/466f220a9b8aa292c8e82b40946be1efded5fb97/public/js/components/app.js#L47) can be safely deleted because t[hat step seems to happen upstream by default](https://github.com/reactjs/react-modal/commit/4d25989#diff-04c6e90faac2675aa89e2176d2eec7d8R72), now?

**Comment by enjalot** [comment]
thank you @stelt and @seemantk! quick and easy fix :+1:
