### ISSUE TITLE
bl.ock rendered incorrectly - two svgs in bl.ock

### ISSUE THREAD

**Issue by kenpenn** [enjalot/blockbuilder#150]
Ian - 

Take a look this : http://bl.ocks.org/mbostock/5872848
and this: http://blockbuilder.org/mbostock/5872848

Issue is, there are two svgs, one width 80, other width 880. 
In blockbuilder, second svg drops below first.
In blockbuilder, if I go into devtools and change width of the second svg to 864, the second svg appears to the right of the first, as intended.

I tried on a 13" and 15" mac, same issue.

Cheers, Ken

**Comment by enjalot** [comment]
it looks like an issue with the default styling of the body element in bl.ocks.org vs. blockbuilder

i think by default chrome puts a 8px margin on the body, but bl.ocks.org sets marginwidth and marginheight attributes to 0 on the body by default.

i'm a little wary of automatically styling user's code because it will look different when they copy it somewhere else. This is why I have the default styling in a fresh block position the body and remove margins when you go to http://blockbuilder.org

**Comment by kenpenn** [comment]
Not an issue with me; it's very rare to have two svgs side by side that
take up the whole width. I'll close this issue.
Thanks for looking into it.

**Comment by enjalot** [comment]
I think it comes down to enforcing what you want with your own styles, rather than relying on the default styles provided by blocks (or any other environment). at the end of the day, the user's css is what matters.
