### ISSUE TITLE
Renderer/iframe Questions

### ISSUE THREAD

**Issue by jgujgu** [enjalot/blockbuilder#184]
Hi Ian,

The work you've done for blockbuilder is quite excellent, very seamless in execution. I read your [blogpost](https://medium.com/@enjalot/architecting-a-sandbox-97b211937911#.eatuyrq1y) and looked through blockbuilder's code and was hoping to confirm some things I assume about the Renderer component with you if you had a moment.

1. Looking at the `src` URL for the iframe, I see that it is a blob (created by the component), but on iframes on bl.ocks, I see that it is a relative URL:
```html
<iframe sandbox="allow-popups allow-scripts allow-forms allow-same-origin" src="/simzou/raw/6459889/be3c560fd84cd13fdbf7f8826f231ee044df5b35/" marginwidth="0" marginheight="0" style="height:500px;" scrolling="no"></iframe>
```
Is it safe to say that bl.ocks probably builds the iframe server side, whereas your implementation builds it in the component?

2. I see that one of the props handed to Renderer is the Gist/Gist data, received asynchronously. Moreover, I understand that any change to the HTML on blockbuilder can be auto-executed. How does the iframe render the files live, if they have not yet been saved to the Gist?

-Jeffrey

**Comment by enjalot** [comment]
Hi Jeffrey,

You're assumptions are correct. In blockbuilder we build the iframe as a blob (essentially one big html file). This allows us to update the code/data live rather than save to the gist and wait for a roundtrip to the server. It also has limitations since we can't include images in the blob for example.

bl.ocks.org acts as a sort of proxy between your browser and the gist api to serve up the files it needs. This makes it more robust but means it can't be updated live.

There is the possibility for some kind of hybrid approach to get around some current limitations in blockbuilder. The code which creates the blob is found here: https://github.com/enjalot/blockbuilder/blob/master/public/js/utils/parseCode.js
which is called from here:
https://github.com/enjalot/blockbuilder/blob/master/public/js/components/renderer.js#L80

feel free to reach out on the d3js slack: https://d3-slackin.herokuapp.com we hang out in the #blockbuilder channel (closing this issue but you can continue commenting here too if you'd like)
hope this helps!
